[tasks.install-target-wasm32-unknown-unknown]
command = "rustup"
args = ["target", "install", "wasm32-unknown-unknown"]

[tasks.install-basic-http-server]
install_crate = { crate_name = "basic-http-server", binary = "basic-http-server", test_arg="--help" }

[tasks.install-wasm-bindgen-cli]
install_crate = { crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen", test_arg="--help" }

[tasks.cargo-build-wasm]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown", "--lib", "--target-dir", "target"]
dependencies = ["install-target-wasm32-unknown-unknown"]

[tasks.wasm-bindgen]
command = "wasm-bindgen"
args = ["--out-dir", "target", "--out-name", "app", "--target", "web", "--no-typescript", "target/wasm32-unknown-unknown/debug/app.wasm"]
dependencies = ["cargo-build-wasm", "install-wasm-bindgen-cli"]

[tasks.serve]
command = "basic-http-server"
args = ["-x"]
dependencies = ["wasm-bindgen", "install-basic-http-server"]