//! TestWorld - A newtype wrapper around Scenario for BDD tests.
//!
//! # Architecture Rule (LOCKED)
//!
//! `TestWorld` MUST be a newtype wrapper around `Option<Scenario>` ONLY.
//! All test state lives in `Scenario`. Do NOT add fields to `TestWorld`.
//! Step bindings delegate to `Scenario` APIs for all operations.
//!
//! # Context-First ABI
//!
//! Steps use capability-separated context types:
//! - Given/When steps: `TestWorldMut` (mutation operations only)
//! - Then steps: `TestWorldRef` (read/assertion operations only, wraps ExpectCtx)

use namako::codegen::{AssertOutcome, StepContext};
use naia_test_harness::{ClientKey, ExpectCtx, Scenario, ToTicks, TrackedClientEvent, TrackedServerEvent};

/// The World type for Naia BDD tests.
///
/// This is a newtype wrapper around `Option<Scenario>`.
/// All test state lives in `Scenario` - do NOT add fields here.
#[derive(Default)]
pub struct TestWorld(Option<Scenario>);

impl TestWorld {
    /// Get the scenario as mutable, panicking if not initialized.
    /// Use this in Given/When steps.
    pub fn scenario_mut(&mut self) -> &mut Scenario {
        self.0.as_mut().expect("Scenario not initialized - call a Given step first")
    }

    /// Get the scenario as immutable, panicking if not initialized.
    /// Use this in Then steps.
    pub fn scenario(&self) -> &Scenario {
        self.0.as_ref().expect("Scenario not initialized - call a Given step first")
    }

    /// Initialize with a new scenario.
    pub fn init(&mut self) -> &mut Scenario {
        self.0.insert(Scenario::new())
    }

    /// Check if scenario is initialized.
    pub fn is_initialized(&self) -> bool {
        self.0.is_some()
    }
}

/// Manual implementation of namako::World to provide custom tick-based polling
/// for Then step assertions.
impl namako::World for TestWorld {
    type Error = std::convert::Infallible;
    type MutCtx<'a> = TestWorldMut<'a>;
    type RefCtx<'a> = TestWorldRef<'a>;

    fn new() -> impl std::future::Future<Output = Result<Self, Self::Error>> {
        async { Ok(Self::default()) }
    }

    fn ctx_mut(&mut self) -> Self::MutCtx<'_> {
        TestWorldMut::new(self)
    }

    fn ctx_ref(&mut self) -> Self::RefCtx<'_> {
        // Note: This is a dummy implementation since TestWorldRef needs ExpectCtx.
        // The actual TestWorldRef is created inside assert_then's polling loop.
        // This will never be called in practice because we override assert_then.
        panic!("ctx_ref() should not be called directly - use assert_then() instead")
    }

    /// Custom tick-based polling for Then step assertions.
    ///
    /// This overrides the default time-based polling with Naia's simulation
    /// tick-based approach using `scenario.until().expect_msg()`.
    fn assert_then<T, F>(&mut self, mut f: F) -> T
    where
        F: FnMut(&Self::RefCtx<'_>) -> AssertOutcome<T>,
    {
        let scenario = self.scenario_mut();
        // Default timeout of 500 ticks for polling assertions
        scenario.until(500.ticks()).expect_msg("BDD Step Assertion", |ctx| {
            let ref_ctx = TestWorldRef::new(ctx);
            match f(&ref_ctx) {
                AssertOutcome::Passed(val) => Some(val),
                AssertOutcome::Pending => None,
                AssertOutcome::Failed(msg) => {
                    // Hard failure - panic immediately, do not retry
                    panic!("Assertion failed: {}", msg);
                },
            }
        })
    }
}

impl std::fmt::Debug for TestWorld {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("TestWorld")
            .field(&self.0.as_ref().map(|_| "Scenario { ... }"))
            .finish()
    }
}

// =============================================================================
// WorldInventory Implementation (normally generated by #[derive(World)])
// =============================================================================

/// Step constructor struct for Given steps.
#[doc(hidden)]
pub struct NamakoGivenTestWorld {
    pub loc: namako::step::Location,
    pub binding_id: &'static str,
    pub expression: &'static str,
    pub kind: &'static str,
    pub impl_hash: &'static str,
    pub captures_arity: u32,
    pub accepts_docstring: bool,
    pub accepts_datatable: bool,
    pub regex: namako::codegen::LazyRegex,
    pub func: namako::Step<TestWorld>,
}

impl namako::codegen::StepConstructor<TestWorld> for NamakoGivenTestWorld {
    fn inner(&self) -> (namako::step::Location, namako::codegen::LazyRegex, namako::Step<TestWorld>) {
        (self.loc, self.regex, self.func)
    }

    fn npap_metadata(&self) -> namako::codegen::NpapBindingMetadata {
        namako::codegen::NpapBindingMetadata {
            binding_id: self.binding_id,
            expression: self.expression,
            kind: self.kind,
            impl_hash: self.impl_hash,
            captures_arity: self.captures_arity,
            accepts_docstring: self.accepts_docstring,
            accepts_datatable: self.accepts_datatable,
        }
    }
}

namako::codegen::collect!(NamakoGivenTestWorld);

/// Step constructor struct for When steps.
#[doc(hidden)]
pub struct NamakoWhenTestWorld {
    pub loc: namako::step::Location,
    pub binding_id: &'static str,
    pub expression: &'static str,
    pub kind: &'static str,
    pub impl_hash: &'static str,
    pub captures_arity: u32,
    pub accepts_docstring: bool,
    pub accepts_datatable: bool,
    pub regex: namako::codegen::LazyRegex,
    pub func: namako::Step<TestWorld>,
}

impl namako::codegen::StepConstructor<TestWorld> for NamakoWhenTestWorld {
    fn inner(&self) -> (namako::step::Location, namako::codegen::LazyRegex, namako::Step<TestWorld>) {
        (self.loc, self.regex, self.func)
    }

    fn npap_metadata(&self) -> namako::codegen::NpapBindingMetadata {
        namako::codegen::NpapBindingMetadata {
            binding_id: self.binding_id,
            expression: self.expression,
            kind: self.kind,
            impl_hash: self.impl_hash,
            captures_arity: self.captures_arity,
            accepts_docstring: self.accepts_docstring,
            accepts_datatable: self.accepts_datatable,
        }
    }
}

namako::codegen::collect!(NamakoWhenTestWorld);

/// Step constructor struct for Then steps.
#[doc(hidden)]
pub struct NamakoThenTestWorld {
    pub loc: namako::step::Location,
    pub binding_id: &'static str,
    pub expression: &'static str,
    pub kind: &'static str,
    pub impl_hash: &'static str,
    pub captures_arity: u32,
    pub accepts_docstring: bool,
    pub accepts_datatable: bool,
    pub regex: namako::codegen::LazyRegex,
    pub func: namako::Step<TestWorld>,
}

impl namako::codegen::StepConstructor<TestWorld> for NamakoThenTestWorld {
    fn inner(&self) -> (namako::step::Location, namako::codegen::LazyRegex, namako::Step<TestWorld>) {
        (self.loc, self.regex, self.func)
    }

    fn npap_metadata(&self) -> namako::codegen::NpapBindingMetadata {
        namako::codegen::NpapBindingMetadata {
            binding_id: self.binding_id,
            expression: self.expression,
            kind: self.kind,
            impl_hash: self.impl_hash,
            captures_arity: self.captures_arity,
            accepts_docstring: self.accepts_docstring,
            accepts_datatable: self.accepts_datatable,
        }
    }
}

namako::codegen::collect!(NamakoThenTestWorld);

impl namako::codegen::WorldInventory for TestWorld {
    type Given = NamakoGivenTestWorld;
    type When = NamakoWhenTestWorld;
    type Then = NamakoThenTestWorld;
}

// =============================================================================
// Context Types for Capability Separation
// =============================================================================

/// Mutable context for Given/When steps.
///
/// This context provides ONLY mutation operations. Assertions and expect
/// operations are not available through this context.
pub struct TestWorldMut<'a>(&'a mut TestWorld);

impl<'a> TestWorldMut<'a> {
    /// Create a new mutable context from a TestWorld.
    pub fn new(world: &'a mut TestWorld) -> Self {
        Self(world)
    }

    /// Get mutable access to the scenario.
    /// Use this for mutation operations in Given/When steps.
    pub fn scenario_mut(&mut self) -> &mut Scenario {
        self.0.scenario_mut()
    }

    /// Initialize with a new scenario.
    pub fn init(&mut self) -> &mut Scenario {
        self.0.init()
    }

    /// Check if scenario is initialized.
    pub fn is_initialized(&self) -> bool {
        self.0.is_initialized()
    }
}

impl StepContext for TestWorldMut<'_> {
    type World = TestWorld;
}

/// Read-only context for Then steps.
///
/// This context wraps an `ExpectCtx` and provides ONLY read/assertion operations.
/// Mutation operations are not available through this context.
///
/// Uses a raw pointer for interior mutability to allow `&self` methods to
/// call ExpectCtx methods that need `&mut self`.
pub struct TestWorldRef<'a> {
    // Raw pointer to ExpectCtx - valid for the lifetime of the closure
    ctx: *mut ExpectCtx<'a>,
}

impl<'a> TestWorldRef<'a> {
    /// Create a new read-only context from an ExpectCtx.
    /// Called by the generated macro wrapper inside the polling loop.
    pub fn new(ctx: &mut ExpectCtx<'a>) -> Self {
        Self { ctx: ctx as *mut ExpectCtx<'a> }
    }

    /// Get access to the underlying ExpectCtx.
    /// Safety: We ensure single-threaded access and the pointer remains valid.
    fn ctx(&self) -> &mut ExpectCtx<'a> {
        // Safety: Tests are single-threaded, pointer is valid for 'a
        unsafe { &mut *self.ctx }
    }

    /// Get the scenario (for delegation).
    fn scenario_ref(&self) -> &Scenario {
        self.ctx().scenario()
    }

    /// Get the current tick count.
    pub fn global_tick(&self) -> usize {
        self.ctx().global_tick()
    }

    /// Get the last client key started.
    pub fn last_client(&self) -> ClientKey {
        self.scenario_ref().last_client()
    }

    /// Check server event ordering.
    pub fn server_event_before(&self, a: TrackedServerEvent, b: TrackedServerEvent) -> bool {
        self.scenario_ref().server_event_before(a, b)
    }

    /// Check if server observed an event.
    pub fn server_observed(&self, event: TrackedServerEvent) -> bool {
        self.scenario_ref().server_event_history().contains(&event)
    }

    /// Check if client observed an event.
    pub fn client_observed(&self, client_key: ClientKey, event: TrackedClientEvent) -> bool {
        self.scenario_ref().client_observed(client_key, event)
    }

    /// Check client event ordering.
    pub fn client_event_before(&self, client_key: ClientKey, a: TrackedClientEvent, b: TrackedClientEvent) -> bool {
        self.scenario_ref().client_event_before(client_key, a, b)
    }

    /// Check if client is connected.
    pub fn client_is_connected(&self, client_key: ClientKey) -> bool {
        self.scenario_ref().client_is_connected(client_key)
    }

    /// Get client event history (cloned).
    pub fn client_event_history(&self, client_key: ClientKey) -> Vec<TrackedClientEvent> {
        self.scenario_ref().client_event_history(client_key).to_vec()
    }

    /// Get server event history (cloned).
    pub fn server_event_history(&self) -> Vec<TrackedServerEvent> {
        self.scenario_ref().server_event_history().to_vec()
    }

    /// Get access to scenario for custom queries (if needed).
    pub fn scenario(&self) -> &Scenario {
        self.scenario_ref()
    }
}

impl StepContext for TestWorldRef<'_> {
    type World = TestWorld;
}
