# Auto-generated by `namako stub --all`
# Delete this file after implementing real scenarios for these bindings.
#
# Per GOLD_PLAN §10.5.2, orphan bindings are a hard error.
# These stubs allow lint to pass while you work on proper scenarios.

@Feature(orphan_stubs)
Feature: Orphan Binding Stubs
  Placeholder scenarios for bindings not yet used by real specifications.

  @Rule(01)
  Rule: Orphan Binding Stubs

    @Deferred @Stub
    @Scenario(01)
    Scenario: Stub for orphan binding 785e108353195a37...
      # Expression: "the system intentionally fails"
      Then the system intentionally fails
