[package]
name = "naia-hecs-shared"
version = "0.10.1"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
description = "Library to faciliate naia & Hecs interop, functionality shared by client & server versions"
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
keywords = ["wasm", "webrtc", "udp", "networking", "gamedev"]
categories = ["network-programming", "game-development", "wasm", "web-programming"]
license = "MIT OR Apache-2.0"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[features]
wbindgen = [ "naia-shared/wbindgen" ]
mquad = [ "naia-shared/mquad" ]

[dependencies]
naia-shared = { version = "0.10", path = "../../../shared" }
hecs = { version = "0.9" }