[package]
name = "naia-basic-client-demo-app"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../.."
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[features]
mquad = [ "naia-client/mquad", "naia-basic-demo-shared/mquad", "miniquad" ]
wbindgen = [ "naia-client/wbindgen", "naia-basic-demo-shared/wbindgen", "log" ]

[dependencies]
naia-client = { path = "../../../../client" }
naia-demo-world = { path = "../../../demo_utils/demo_world" }
naia-basic-demo-shared = { path = "../../shared" }
cfg-if = { version = "1.0" }
log = { version = "0.4", optional = true }
miniquad = { version = "=0.3.11", features = ["log-impl"], optional = true }