[package]
name = "naia-macroquad-demo-shared"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[features]

[dependencies]
naia-shared = { path = "../../../shared", features = ["mquad"] }
cfg-if = { version = "1.0" }
log = { version = "0.4" }