[tasks.install-target-wasm32-unknown-unknown]
command = "rustup"
args = ["target", "install", "wasm32-unknown-unknown"]

[tasks.install-basic-http-server]
install_crate = {crate_name = "basic-http-server", binary = "basic-http-server", test_arg="--help"}

[tasks.cargo-build-wasm]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown", "--target-dir", "target"]
dependencies = ["install-target-wasm32-unknown-unknown"]

[tasks.delete-old-wasm]
command = "rm"
args = ["-f", "target/naia_macroquad_client_demo.wasm"]
dependencies = ["cargo-build-wasm"]

[tasks.move-wasm]
command = "mv"
args = ["target/wasm32-unknown-unknown/debug/naia_macroquad_client_demo.wasm", "target/naia_macroquad_client_demo.wasm"]
dependencies = ["delete-old-wasm"]

[tasks.serve]
command = "basic-http-server"
args = ["-x"]
dependencies = ["move-wasm", "install-basic-http-server"]
