[package]
name = "naia-hecs-server"
version = "0.8.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
description = "Library to faciliate naia_server & Hecs interop"
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
keywords = ["wasm", "webrtc", "udp", "networking", "gamedev"]
license = "MIT OR Apache-2.0"
categories = ["network-programming", "game-development", "wasm", "web-programming"]
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[features]
use-udp = [ "naia-server/use-udp" ]
use-webrtc = [ "naia-server/use-webrtc" ]

[dependencies]
naia-server = { version = "=0.7.4", path = "../../../server" }
naia-hecs-shared = { version = "0.8", path = "../shared" }
hecs = { version = "=0.5.2" }