[package]
name = "naia-socket-client-demo-mq"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../.."
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[features]

[dependencies]
naia-socket-client-demo-app = { path = "../app", features = [ "mquad" ] }
miniquad = { version = "=0.3.0-alpha.45", features = ["log-impl"] }