use std::time::Duration;

use naia_socket_shared::LinkConditionerConfig;

use crate::{Manifest, PingConfig, Protocolize};

/// Contains Config properties which will be shared by Server and Client
pub struct SharedConfig<P: Protocolize> {
    /// The Manifest generated by the Protocol which handles Replication
    pub manifest: Manifest<P>,
    /// The duration between each tick
    pub tick_interval: Option<Duration>,
    /// Configuration used to simulate network conditions
    pub link_condition_config: Option<LinkConditionerConfig>,
    /// Configuration used to monitor the ping & jitter on the network
    pub ping_config: Option<PingConfig>,
}

impl<P: Protocolize> SharedConfig<P> {
    /// Creates a new SharedConfig
    pub fn new(
        manifest: Manifest<P>,
        tick_interval: Option<Duration>,
        link_condition_config: Option<LinkConditionerConfig>,
        ping_config: Option<PingConfig>,
    ) -> Self {
        SharedConfig {
            manifest,
            tick_interval,
            link_condition_config,
            ping_config,
        }
    }
}
