[package]
name = "naia-tickless-demo-shared"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[features]

[dependencies]
naia-shared = { path = "../../../shared" }
naia-derive = { path = "../../../derive" }
cfg-if = "=1.0.0"
log = "0.4"
nanoserde = "0.1.17"