[package]
name = "naia-socket-client-demo-app"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../.."
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[features]
mquad = [ "naia-client-socket/mquad", "naia-socket-demo-shared/mquad", "naia-shared/mquad", "miniquad" ]
wbindgen = [ "naia-client-socket/wbindgen", "naia-socket-demo-shared/wbindgen", "naia-shared/wbindgen", "log" ]

[dependencies]
naia-client-socket = { path = "../../../../socket/client" }
naia-socket-demo-shared = { path = "../../shared" }
naia-shared = { path = "../../../../shared" }
cfg-if = "0.1.10"
log = { version = "0.4", optional = true }
miniquad = { version = "=0.3.0-alpha.45", features = ["log-impl"], optional = true }